version: "3"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile.static
    pull_policy: build
    image: git.local.puvvadi.net/kd/blog:static
    container_name: blog
    environment:
      TZ: 'Asia/Kolkata'
    dns:
      - 10.10.10.10
      - 1.1.1.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.entrypoints=http"
      - "traefik.http.routers.blog.rule=Host(`blog.local.puvvadi.net`)"
      - "traefik.http.routers.blog.middlewares=pihole-https-redirect"
      - "traefik.http.middlewares.blog-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.blog-secure.entrypoints=https"
      - "traefik.http.routers.blog-secure.rule=Host(`blog.local.puvvadi.net`)"
      - "traefik.http.routers.blog-secure.tls=true"
      - "traefik.http.routers.blog-secure.service=blog"
      - "traefik.http.services.blog.loadbalancer.server.port=4000"
      - "traefik.http.services.blog.loadbalancer.server.scheme=http"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
  proxy:
    external: true
