# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
baseurl: ""
lang: en
timezone: Asia/Kolkata

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: KD's Blog

tagline: Engineer, DevOps, Geek, Ansible, Terraform

description: >-
  Personal tech blog with Devops, Serverless and more. Ansible, terraform, omada,
url: "https://blog.puvvadi.me"
github:
  username: kdpuvvadi
  repository_url: https://github.com/kdpuvvadi/blog
twitter:
  username: kdpuvvadi

social:
  name: KD Puvvadi
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/kdpuvvadi
    - https://infosec.exchange/@kdpuvvadi
    - https://bsky.app/profile/puvvadi.net
    - https://twitter.com/kdpuvvadi

google_site_verification: # fill in to your verification string

analytics:
  goatcounter:
    id: kdpuvvadi

theme_mode: dark
cdn:
avatar: https://avatars.githubusercontent.com/u/7326255?v=4
toc: true

comments:
  provider: giscus
  giscus:
    repo: kdpuvvadi/blog
    repo_id: 'MDEwOlJlcG9zaXRvcnkzMDkyOTI1NzI='
    category: General
    category_id: 'DIC_kwDOEm9uHM4CSN_-'
    mapping: 'og:title'
    input_position:
    lang: en
    reactions_enabled: 1

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true

paginate: 10

pageviews:
  provider: goatcounter

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - terraform
  - .github

include:
  - _redirects

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
