baseurl = "/"
paginate = 5

googleAnalytics = "251568676"

[params]

  title = "KD's Blog"
  subtitle = "Simply Tech"
  owner = "KD"
  keywords = "Omada, contact form, blog, dev, vercel, cloudflare, pages, netlify, hugo, home assistant, Automation, google forms, docker, portainer, kubctl, terraform, ansible, aws, digitalocean"
  copyright = "KD Puvvadi"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  # favicon = "favicon.ico"
  readingTime = true # default
  enableGitInfo = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"

  toc = false

  socialshare = false

  [params.logo]
    logoText = ">_ KD's Blog"
    logoHomeLink = "/"

  [[menu.main]]
    identifier = "home"
    weight = 1
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "about"
    weight = 2
    name = "About"
    url = "https://kd.puvvadi.me/"
    [menu.main.params]
      newTab = true

  [[menu.main]]
    identifier = "contact"
      weight = 3
    name = "Contact"
    url = "/contact"

  [params.social.share]
    facebook = true
    twitter = true
    whatsapp = true

  [params.twitter]
    creator = "kdpuvvadi"
    site = "kdpuvvadi"
