baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

googleAnalytics = "UA-164525361-1"

[params]
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  disqusShortname = "blog-puvvadi-me"


  enableGitInfo = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"


[params.twitter]
  creator = "kdpuvvadi"
  site = "kdpuvvadi"

[languages]
  [languages.en]
    languageName = "English"
    title = "KD's Blog"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = ">_ KD's Blog"
      logoHomeLink = "/"

    [[menu.main]]
      identifier = "home"
      weight = 1
      name = "Home"
      url = "/"

    [[menu.main]]
      identifier = "about"
      weight = 2
      name = "About"
      url = "https://kd.puvvadi.me/"
    [[menu.main]]
      identifier = "contact"
        weight = 3
      name = "Contact"
      url = "/contact"