FROM ruby:alpine3.19 as base
LABEL version="4.0"

ENV TZ Asia/Kolkata

RUN apk --no-cache upgrade --purge
RUN apk --no-cache add build-base git

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
RUN bundle exec jekyll build --config  _config.yml --incremental

FROM nginx:stable-alpine
COPY --from=base /usr/src/app/_site /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
