version: "3"

services:
  build:
    build: .
    image: kdpuvvadi/blog:latest
    container_name: blog
    ports:
      - "4000:4000"
  docker:
    extends: build
    image: kdpuvvadi/blog:4.0.0
  ghcr:
    extends: build
    image: ghcr.io/kdpuvvadi/blog:4.0.0
