FROM ruby:3.3.6-alpine3.20 AS base

ENV TZ=Asia/Kolkata

RUN apk --no-cache upgrade --purge
RUN apk --no-cache add build-base git

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

ENV JEKYLL_ENV=production

COPY . .
RUN bundle exec jekyll build

FROM nginx:stable-alpine
COPY --from=base /usr/src/app/_site /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
