name: build

on:
  workflow_dispatch:
  release:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale login
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          config-inline: |
            [dns]
              nameservers=["100.106.243.93","100.78.173.17"]

      - name: Get commit short sha
        id: vars
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$shortSha"

      - name: Log into github
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into gitea
        uses: docker/login-action@v3.0.0
        with:
          registry: git.local.puvvadi.net
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Log into registry docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to docker, github hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ github.repository	}}:${{ steps.vars.outputs.short_sha }}
            ghcr.io/${{ github.repository	}}:${{ steps.vars.outputs.short_sha }}
            ${{ github.repository	}}:latest
            ghcr.io/${{ github.repository	}}:latest
            git.local.puvvadi.net/${{ secrets.GITEA_USER }}/${{ github.repository	}}:${{ steps.vars.outputs.short_sha }}
            git.local.puvvadi.net/${{ secrets.GITEA_USER }}/${{ github.repository	}}:latest
