name: static builds

on:
  workflow_dispatch:
  release:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale login
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.62.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
        with:
          buildkitd-config-inline: |
            [dns]
              nameservers=["100.106.243.93"]

      - name: Log into github
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into gitea
        uses: docker/login-action@v3.1.0
        with:
          registry: git.local.puvvadi.net
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Log into registry docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to docker, github hub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile.static
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository	}}:static
            ghcr.io/${{ github.repository	}}:static
            git.local.puvvadi.net/kd/blog:static
          cache-from: type=registry,ref=${{ github.repository	}}:static
          cache-to: type=inline
